[package]
name = "bonanca-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "bonanca"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["experimental-async"] }
bonanca-wallets = { path = "../bonanca-wallets" }