[workspace]
resolver = "3"
members = ["crates/*"]

[package]
name = "bonanca"
version = "0.1.0"
edition = "2024"
description = "A CLI for managing crypto index funds"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.41", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
bonanca-core = { path = "./crates/bonanca-core" }
bonanca-managers = { path = "./crates/bonanca-managers" }