[package]
name = "bonanca-keyvault"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39 = {version = "2.2.0", features = ["all-languages", "rand"]}
ed25519-dalek-bip32 = "0.3.0"
solana-sdk = "3.0.0"
