[package]
name = "bonanca-lending"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.1.2"
anchor-client = { version = "0.32.1", features = ["async"] }
anchor-lang = "0.32.1"
anyhow.workspace = true
async-trait = "0.1.89"
tokio = "1.48.0"
