[package]
name = "index"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bonanca = { path = "../../../" }
clap = { version = "4.5.41", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
